params:
  # ----------------------------------------------------------------------------
  - symbol: "f2094ae"
    value: "$(var use_case_base_tree_path_absolute)/$(var tree)"
    mode: literal
    files:
      - $HOME/Desktop/de-ref/test-files/file1.txt
  # ----------------------------------------------------------------------------
  - symbol: "37ec171"
    value: "$HOME"
    mode: literal
    files:
      - /home/member/Desktop/de-ref/test-files/file2.txt
# ----------------------------------------------------------------------------
